version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"   # RabbitMQ Management Console
      - "5672:5672"     # AMQP Protocol
    environment:
      RABBITMQ_DEFAULT_USER: user       # Username
      RABBITMQ_DEFAULT_PASS: password   # Password
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
